pipeline {
    agent any

    environment {
        VERSION = '1.1.0'
    }

    stages {
        stage('Checkout') {
            steps {
               checkout([$class: 'GitSCM',
                    branches: [[name: '*/main']],
                    userRemoteConfigs: [[
                        url: 'git@github.com:oLeoBarreto/LinkHub.git',
                        credentialsId: 'Github'
                    ]]
                ])
            }
        }
        stage('Build') {
            steps {
                dir('shortener-service') {
                    sh 'chmod +x gradlew'
                    sh './gradlew build -x detekt'
                }
            }
        }
        stage('Tests') {
            steps {
                dir('shortener-service') {
                    sh './gradlew test'
                    junit 'build/test-results/test/*.xml'
                }
            }
        }
        stage('Code quality') {
            steps {
                dir('shortener-service') {
                    script {
                        try {
                            sh './gradlew detekt'
                        }
                        catch(Exception e) {
                            print("${e}")
                        }
                    }
                }
            }
        }
        stage('Approve for publish on DockerHub') {
            steps {
                input message:'Build docker image and publish to DockerHub?', ok: 'Yes, build it!', cancel: 'No, skip this step!'
            }
        }
        stage('Build & Push docker image') {
            steps {
                dir('shortener-service') {
                    script {
                        docker.withRegistry('https://registry.hub.docker.com', 'DockerHub') {
                            def dockerImage = docker.build('leobarreto/shortener-service:${VERSION}', '.')
                            dockerImage.push()
                        }
                    }
                }
            }
        }
    }

    post {
        always {
            archiveArtifacts artifacts: 'shortener-serviced/build/libs/*.jar', allowEmptyArchive: true
        }
        success {
            echo "Pipeline executed with success!"
        }
        failure {
            echo "Pipeline failure!"
        }
    }
}