pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
               checkout([$class: 'GitSCM',
                    branches: [[name: '*/main']],
                    userRemoteConfigs: [[
                        url: 'git@github.com:oLeoBarreto/LinkHub.git',
                        credentialsId: 'Github'
                    ]]
                ])
            }
        }
        stage('Build') {
            steps {
                dir('shortener-service') {
                    sh 'chmod +x gradlew'
                    sh './gradlew build'
                }
            }
        }
        stage('Tests') {
            steps {
                dir('shortener-service') {
                    sh './gradlew test'
                    junit 'build/test-results/test/*.xml'
                }
            }
        }
    }

    post {
        always {
            archiveArtifacts artifacts: 'build/libs/*.jar', allowEmptyArchive: true
        }
        success {
            echo "Pipeline executed with success!"
        }
        failure {
            echo "Pipeline failure!"
        }
    }
}