version: "3.5"

services: 
  shortener-service:
    image: leobarreto/shortener-service:1.0.0
    container_name: shortener-service
    ports:
      - 8082:8082
    environment:
      - DB_URL=jdbc:postgresql://host.docker.internal:4510/linkhub_db
      - DB_USER=admin
      - DB_PASSWORD=admin
      - AWS_ACCESS_KEY=mock_access_key
      - AWS_SECRET_KEY=mock_secret_key
      - AWS_REGION=us-east-1
      - AWS_CUSTOM_ENDPOINT=http://host.docker.internal:4566
      - PORT=8082

  analytics-service:
    image: leobarreto/analytics-service:1.0.0
    container_name: analytics-service
    ports:
      - 8081:8081
    environment:
      - AWS_ACCESS_KEY=mock_access_key
      - AWS_SECRET_KEY=mock_secret_key
      - AWS_REGION=us-east-1
      - AWS_CUSTOM_ENDPOINT=http://host.docker.internal:4566

  jenkins:
    container_name: jenkins
    build:
      context: .
    ports:
      - 8080:8080
    user: root
    volumes:
      - jekins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jenkins

volumes:
  postgres_data:
  jekins_data:

networks:
  jenkins:
    driver: bridge
    