version: "3.5"

services: 
  shortener-service:
    image: leobarreto/shortener-service:1.0.0
    container_name: shortener-service
    ports:
      - 8082:8082
    environment:
      - DB_URL=jdbc:postgresql://host.docker.internal:4510/linkhub_db
      - DB_USER=admin
      - DB_PASSWORD=admin
      - AWS_ACCESS_KEY=mock_access_key
      - AWS_SECRET_KEY=mock_secret_key
      - AWS_REGION=us-east-1
      - AWS_CUSTOM_ENDPOINT=http://host.docker.internal:4566
      - PORT=8082
    networks:
      - linkhub

  analytics-service:
    image: leobarreto/analytics-service:1.0.0
    container_name: analytics-service
    ports:
      - 8081:8081
    environment:
      - AWS_ACCESS_KEY=mock_access_key
      - AWS_SECRET_KEY=mock_secret_key
      - AWS_REGION=us-east-1
      - AWS_CUSTOM_ENDPOINT=http://host.docker.internal:4566
    networks:
      - linkhub

  jenkins:
    container_name: jenkins
    build:
      context: .
    ports:
      - 8080:8080
    user: root
    volumes:
      - jekins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - linkhub

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana-service
    restart: unless-stopped
    environment:
      - GF_AUTH_ANONYMOUS=false
      - GF_SECURITY_ALLOW_EMVEDDING=true
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - linkhub
  
  prometheus:
    image: prom/prometheus
    container_name: prometheus-service
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - linkhub

  loki:
    image: grafana/loki
    container_name: loki-grafana-service
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - linkhub

volumes:
  postgres_data:
  jekins_data:
  grafana_data:
  prometheus_data:

networks:
  linkhub:
    driver: bridge
    