pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
               checkout([$class: 'GitSCM',
                    branches: [[name: '*/main']],
                    userRemoteConfigs: [[
                        url: 'git@github.com:oLeoBarreto/LinkHub.git',
                        credentialsId: 'Github'
                    ]]
                ])
            }
        }
        stage('Build') {
            steps {
                dir('linkhub-app') {
                    nodejs(nodeJSInstallationName: 'node LTS') {
                        sh 'npm install'
                        sh 'npm run build'
                    }
                }
            }
        }
        stage('Approve for publish on DockerHub') {
            steps {
                input message:'Build docker image and publish to DockerHub?', ok: 'Yes, build it!', cancel: 'No, skip this step!'
            }
        }
        stage('Build & Push docker image') {
            steps {
                dir('linkhub-app') {
                    script {
                        docker.withRegistry('https://registry.hub.docker.com', 'DockerHub') {
                            def dockerImage = docker.build('leobarreto/linkhub-app:1.0.0', '.')
                            dockerImage.push()
                        }
                    }
                }
            }
        }
    }

    post {
        always {
            archiveArtifacts artifacts: 'linkhub-app/.next/standalone/**', allowEmptyArchive: true
        }
        success {
            echo "Pipeline executed with success!"
        }
        failure {
            echo "Pipeline failure!"
        }
    }
}