ktor:
    application:
        modules:
            - com.leobarreto.ApplicationKt.module
    deployment:
        port: ${PORT:8081

postgres:
    url: ${DB_URL}
    user: ${DB_USER}
    password: ${DB_PASSWORD}

aws:
    access_key: ${AWS_ACCESS_KEY}
    secret_key: ${AWS_SECRET_KEY}
    region: ${AWS_REGION}
    custom_endpoint: ${AWS_CUSTOM_ENDPOINT:""}
