ktor:
    application:
        modules:
            - com.leobarreto.ApplicationKt.module
    deployment:
        port: ${PORT:8081

aws:
    access_key: ${AWS_ACCESS_KEY}
    secret_key: ${AWS_SECRET_KEY}
    region: ${AWS_REGION}
    custom_endpoint: ${AWS_CUSTOM_ENDPOINT:""}
